# Generated by Django 5.2.14 on 2026-05-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='controlusers',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='controlusers',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='controlusers',
            name='imgs',
        ),
        migrations.RemoveField(
            model_name='controlusers',
            name='username',
        ),
        migrations.AddField(
            model_name='controlusers',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='controlusers',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='controlusers',
            name='phon',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
