# Generated by Django 5.2.14 on 2026-05-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_controlusers_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlusers',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
