# Generated by Django 5.2.14 on 2026-05-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_controlusers_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlusers',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=14, null=True),
        ),
    ]
